#pragma once

#define EXPERIMENT_TEXT_PREDICTION 0
#define EXPERIMENT_CIFAR 1
#define EXPERIMENT_RNN_BENCHMARK 2
#define EXPERIMENT_TIMESERIES 3
#define EXPERIMENT_MNIST_VIDEO 4

#define EXPERIMENT_SELECTION EXPERIMENT_TEXT_PREDICTION